spring.application.name=ApI-GateWay
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


#Routing logic product
spring.cloud.gateway.routes[0].id=Product-Service
spring.cloud.gateway.routes[0].uri=lb://Product-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/place

spring.cloud.gateway.routes[1].id=Notification-Service
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-API
spring.cloud.gateway.routes[1].predicates[0]=Path=/amazon/fetch

server.port=3333